
version: '3.3'

services:
  cronjob:
    container_name: ${CRONJOB_CONTAINER_NAME}
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - backups:${BACKUP_DIR}
    environment:
      BACKUP_DIR: ${BACKUP_DIR}
      DAYS_TO_KEEP: ${DAYS_TO_KEEP}
      FILE_SUFFIX: ${FILE_SUFFIX}
      SSH_USERNAME: ${SSH_USERNAME}
      SSH_HOST: ${SSH_HOST}
      SSH_PORT: ${SSH_PORT}
      REMOTE_SOURCE_PATH: ${REMOTE_SOURCE_PATH}
  fileBrowser:
    container_name: ${FILE_BROWSER_CONTAINER_NAME}
    image: filebrowser/filebrowser
    ports:
      - ${FILE_BROWSER_PORT}:80
    volumes:
        - backups:/srv

volumes:
  backups:
    driver: local
    driver_opts:
      type: none
      device: ${BACKUP_DIR}
      o: bind

